### ISSUE TITLE
关于item embedding更新时无非线性激活函数的问题

### ISSUE THREAD

**Issue by FelixHilyer** [xiaxin1998/COTREC#1]
您好！
  model.py中第47行，更新item embedding时，似乎只进行了线性变换而未进行非线性激活，这里有什么说法吗？

**Comment by xiaxin1998** [comment]
你好 感谢对我们的论文感兴趣
其实在论文里有说道，我们采用的是SGC，非线性激活函数是冗余的，对模型效果没有帮助。这个技术最早在Simplifying Graph Convolutional Networks这篇论文提出来，你可以参考一下。

**Comment by anunverse** [comment]
非常感谢！

**Comment by FelixHilyer** [comment]
> 你好 感谢对我们的论文感兴趣
> 其实在论文里有说道，我们采用的是SGC，非线性激活函数是冗余的，对模型效果没有帮助。这个技术最早在Simplifying Graph Convolutional Networks这篇论文提出来，你可以参考一下。

  非常感谢！
