### ISSUE TITLE
关于模型初始化

### ISSUE THREAD

**Issue by Nishikata97** [xiaxin1998/COTREC#12]
https://github.com/xiaxin1998/COTREC/blob/5a4884746329bca804b1f9c508b37498812ba355/model.py#LL124C18-L124C18

`def init_parameters(self):`
`     stdv = 1.0 / math.sqrt(self.item_dim)`
`     for weight in self.parameters():`
`          weight.data.uniform_(-stdv, stdv)`

我查阅了几篇session-based recommendations的baselines工作，SR-GNN、GCE-GNN这两个工作在实验章节均提到模型参数使用均值为0且标准差为0.1的高斯分布进行初始化，但在代码实现上却使用上述均匀分布 (weight.data.uniform_(-stdv, stdv)) 的方式，请问下这是一处小错误吗。

**Comment by xiaxin1998** [comment]
是的 是一个小错误 应该是均匀分布 不好意思

**Comment by Nishikata97** [comment]
非常感谢！
