### ISSUE TITLE
About Itemconv and Sessconv

### ISSUE THREAD

**Issue by MTandHJ** [xiaxin1998/COTREC#15]
Hi,

I found the weights in Itemconv and Sessconv are collected in a normal dictionary instead of `torch.nn.ModuleDict`. It seems that, in this vein, the weights cannot be successfully found by calling `parameters()` and thus they would not be trained.

Thanks !

**Comment by xiaxin1998** [comment]
Hello,

Thanks for your interest. I have updated our codes by using ModuleList. 
And we got a little better results than before.
