### ISSUE TITLE
关于model.py中mrr指标计算时，target是否需要减1的问题

### ISSUE THREAD

**Issue by FelixHilyer** [xiaxin1998/COTREC#2]
您好！
  在阅读model.py第338行时我发现，target未进行减1操作，对于此处prediction的值应该是从0开始，而target的值是从1开始，此处是否应写成np.where(prediction == target - 1)[0]。
  谢谢！

**Comment by xiaxin1998** [comment]
你好 
在util.py文件里 get_slice函数返回targets的时候 已经减1了
