### ISSUE TITLE
关于验证集

### ISSUE THREAD

**Issue by FelixHilyer** [xiaxin1998/COTREC#3]
您好！
  请问一下代码是没有划分验证集吗，只有训练集和测试集吗？
  这是我第三次向您询问了，每次问的问题都很傻，打扰您了，十分抱歉。
  谢谢！

**Comment by xiaxin1998** [comment]
你好 验证机是随机在训练集抽取的百分之十 用来调参 我代码里好像没有体现 你可以直接随机抽取就行了
no worries 请随意提问

**Comment by FelixHilyer** [comment]
> 你好 验证机是随机在训练集抽取的百分之十 用来调参 我代码里好像没有体现 你可以直接随机抽取就行了
> no worries 请随意提问

请问这里是保存模型的超参数吗，还是将验证集上最好的那一轮的模型权重参数保存下来呢

**Comment by xiaxin1998** [comment]
验证机就是用来找到最好的超参数的 模型权重参数是随着训练变化的 没有必要保存这个

**Comment by FelixHilyer** [comment]
非常感谢！！！无以言表
