### ISSUE TITLE
关于计算Model文件中np.sum(final_cpu, 0)的报错

### ISSUE THREAD

**Issue by Andy20178** [xiaxin1998/COTREC#4]
在运行过程中，ItemConv类的forward函数中，在最后计算item_embeddings = np.sum(final, 0)/(self.layers+1)时，报错TypeError: can‘t convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first。
想知道怎么改这个错，感谢！

**Comment by xiaxin1998** [comment]
Thanks for your interest in our paper.
Actually, the error is caused by different version.
I suggest you change your versions to Python3, Pytorch 1.6.0, Numpy 1.18.1.

**Comment by kingmbc** [comment]
Hi. I try to reproduce the code. Can we do it like below?

```python
        #item_embeddings = np.sum(final, 0)/(self.layers+1)
        item_embeddings = torch.sum(torch.stack(final),dim=0)/(self.layers+1)
```

**Comment by Andy20178** [comment]
OK, that's what I do when I run the code.
