### ISSUE TITLE
关于data mask生成的一个疑问

### ISSUE THREAD

**Issue by Zachary-ZS** [xiaxin1998/COTREC#5]
https://github.com/xiaxin1998/COTREC/blob/c80c4d1f37cc2e0495b1588eb063481a882f8ad5/util.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L16

这里data mask没理解错的话应该是要生成邻接矩阵吧，这里sess[i]第一次出现的时候，如果sess[i+1] == sess[i]，比如都是项目k，那么邻接矩阵里k到k不应该再加1变为2吗，按这里的话就忽略了一次变成1；这儿应该是个小bug？
（举例：一个session 1 -> 2 ->2 ->5，假如2是第一次出现，那么字典里2->2的次数按理说是2，但是按代码就是1）

**Comment by xiaxin1998** [comment]
你好 这个地方并不能算是一个bug 邻接矩阵的对角线地方 我们可以默认自连接的时候的值就是1 当然你也可以规定对角线上也可以大于一
