### ISSUE TITLE
itemConv代码问题

### ISSUE THREAD

**Issue by SUSTechBruce** [xiaxin1998/COTREC#6]
itemConV中的numpy的求和计算报错，改为torch tensor计算后出现程序卡顿无法无法显示运行

**Comment by SUSTechBruce** [comment]
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
当我改成 final = [item_embed.cpu().detach().numpy() for item_embed in final]后，程序卡死并无法运行训练过程，请问作者能尽快回复这个问题吗？

**Comment by SUSTechBruce** [comment]
请问一下作者，算法一般几个epoch才收敛？感觉在训练的速度很慢而且第四个epoch，MRR 和 hit rate都非常低
start predicting:  2021-11-15 15:48:08.287063
{'hit5': 18.673234811165845, 'mrr5': 13.443158182813356, 'hit10': 21.20689655172414, 'mrr10': 13.78161310501212, 'hit20': 23.853858784893266, 'mrr20': 13.9645847848924}
train_loss:     64079.1231      Recall@5: 19.4433       MRR5: 13.7103   Epoch: 0,  0
train_loss:     64079.1231      Recall@10: 21.9901      MRR10: 14.0533  Epoch: 0,  0
train_loss:     64079.1231      Recall@20: 24.4236      MRR20: 14.2229  Epoch: 0,  0

**Comment by xiaxin1998** [comment]
你好 遇到那个error是由于版本问题 这个现有的唯一解决办法就是用和我们一样的版本 如果你不更新版本 而是把那两行代码改成能运行的代码 结果就会不正常 所以正确的办法是改变版本 不知道你这个是哪个数据集 你的训练时间是多少？
