### ISSUE TITLE
关于测试集进行shuffle这件小事

### ISSUE THREAD

**Issue by FelixHilyer** [xiaxin1998/COTREC#7]
作者您好！想请问一下在测试集上进行shuffle的想法是什么？
  对于session recommendation，由于进行了数据增强，[1,2,3,4,5]会拆分成[1,2,3]->[4],[1,2,3,4]->[5]这样的序列，在测试集上建立全局图时若不shuffle会导致建立的图易受较长序列的影响（[1,2,3]->[4],[1,2,3,4]->[5]在同一个batch中，即会在同一张大图中），然而测试集上loss不反传，对模型及实验结果似乎并无影响，此处是否不需进行shuffle。
  十分期待您的回复。

**Comment by xiaxin1998** [comment]
您好
实际上 在测试集上是不应该建图的 你可以从代码中看出来 我们并没有在测试集上建图
测试机上shuffle不shuffle是无所谓的 因为实际做预测的时候你只能看到一个给定的session
