### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by ZQSong1997** [xiaxin1998/COTREC#9]
您好，根据你们所提供的数据集下载链接，从Dropbox上下载下来的各个txt文件打开发现都是乱码，不知道是不是编码的原因，我尝试了转换编码（如utf-8，unicode）可是也不行，请问这些什么原因呢？

另外，请问方便提供一下关于数据预处理的代码吗？谢谢！

**Comment by xiaxin1998** [comment]
readme里面有说是用pickle编码的
预处理可以看：https://github.com/CCIIPLab/GCE-GNN/blob/master/datasets/process_tmall.py
https://github.com/SamHaoYuan/DSANForAAAI2021
